name: Check Truth

# Controls when the action will run.
on:
  workflow_dispatch:
  schedule:
    - cron: "0 13 * * *"

jobs:
  build:
    runs-on: ubuntu-latest
    if: github.repository == 'epiforecasts/covid19-forecast-hub-europe'
    steps:
    - uses: actions/checkout@master
      with:
        fetch-depth: 0 # otherwise, you will failed to push refs to dest repo

    - name: Setup R
      uses: r-lib/actions/setup-r@v1

    - name: Setup Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x' # Version range or exact version of a Python version to use, using SemVer's version range syntax
        architecture: 'x64' # optional x64 or x86. Defaults to x64 if not specified

    - name: Install python requirenments
      run: |
        pip3 install -r github-actions/pr_requirements.txt

    - name: Install R requirenments
      run: |
        sudo apt-get install pandoc libcurl4-openssl-dev
        Rscript -e 'install.packages(c("gh", "dplyr", "stringr", "here", "knitr", "rmarkdown", "readr", "tibble", "countrycode"))'

    - name: Verify truth data
      run: |
        python3 code/validation/check_truth.py

    - name: Create status page
      run: |
        Rscript -e 'rmarkdown::render("data-truth/data-issues.Rmd")'

    - name: Commit files
      env:
        AUTH: ${{ secrets.GITHUBTOKEN }}
      run: |
        git config user.email "action@github.com"
        git config user.name "GitHub Action - check truth
        git add --all
        git commit -m "Check truth data"
        git push 
        echo "pushed to github"
