name: "LANL"
on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"

jobs:
  get_lanl:
    runs-on: ubuntu-20.04
    if: github.repository == 'epiforecasts/covid19-forecast-hub-europe'
    env:
      RSPM: "https://packagemanager.rstudio.com/cran/__linux__/focal/latest"
    steps:
    - uses: actions/checkout@master
    - uses: r-lib/actions/setup-r@v1

    - name: Install system dependencies
      run: sudo apt-get install libudunits2-dev libcurl4-openssl-dev libgdal-dev

    - name: Install R dependencies
      run: Rscript -e 'install.packages(c("lubridate", "here", "vroom", "dplyr", "tidyr", "readr", "janitor"))'

    - name: LANL forecasts
      run: Rscript 'code/auto_download/auto-download-lanl-covid19.r'

    - name: Commit files
      env:
        AUTH: ${{ secrets.GITHUBTOKEN }}
      run: |
        git config user.email "action@github.com"
        git config user.name "GitHub Action - LANL"
        git add --all
        git commit -m "LANL - weekly" || echo "No changes to commit"
        git push
