name: "Create ensemble report"
on:
  workflow_dispatch:
  schedule:
    - cron: "45 10 * * 2"
jobs:
  ensemble_report:
    runs-on: ubuntu-20.04
    if: github.repository == 'epiforecasts/covid19-forecast-hub-europe'
    env:
      RSPM: "https://packagemanager.rstudio.com/cran/__linux__/focal/latest"
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
    steps:
    - uses: actions/checkout@v2
    - uses: r-lib/actions/setup-r@v1

    - name: Install system dependencies
      run: sudo apt-get install -y libssl-dev libcurl4-openssl-dev pandoc

    - name: Install R dependencies
      run: |
        install.packages(c("remotes", "here", "rmarkdown", "lubridate", "ggplot2", "dplyr", "DT", "knitr", "readr", "rlang"))
        remotes::install_github("reichlab/covidHubUtils")
        remotes::install_github("epiforecasts/scoringutils@limit-viz")
        remotes::install_github("epiforecasts/EuroForecastHub")
      shell: Rscript {0}

    - name: Create ensemble reports
      run: Rscript 'code/reports/compile-ensemble-report.r'

    - name: Push to web site
      uses: dmnemec/copy_file_to_another_repo_action@main
      env:
        API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
      with:
        source_file: 'html/.'
        destination_repo: 'epiforecasts/covid19-forecast-hub-europe-website'
        destination_folder: 'reports'
        user_email: 'action@github.com'
        user_name: 'GitHub Action - ensemble report'
        commit_message: 'Ensemble report'

    - name: Create issue about failure
      if: failure()
      uses: JasonEtco/create-an-issue@v2.5.0
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        filename: .github/action-issue-template.md
