name: "Visualization/Validation/Evaluation"
on:
  workflow_dispatch:
  schedule:
    - cron: "0 17 * * *"
  

jobs:
  build:
    runs-on: ubuntu-latest
    if: github.repository == 'epiforecasts/covid19-forecast-hub-europe'
    steps:
    - uses: actions/checkout@master
      with:
        fetch-depth: 0 # otherwise, you will failed to push refs to dest repo
    - name: Setup R
      run: |
         sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-keys E298A3A825C0D65DFD57CBB651716619E084DAB9
         sudo add-apt-repository 'deb https://cloud.r-project.org/bin/linux/ubuntu bionic-cran40/'
         sudo apt update
         sudo apt install r-base
    - name: Setup Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x' # Version range or exact version of a Python version to use, using SemVer's version range syntax
        architecture: 'x64' # optional x64 or x86. Defaults to x64 if not specified
    - name: Install requirenments
      run: |
        pip3 install -r github-actions/pr_requirements.txt
    - name: Visualization
      run: |
        python3 ./viz/prepare_truth_data.py
        python3 ./viz/prepare_forecast_data.py
#     - name: Validation
#       run: |
#         cd ./code/validation
#         python3 code/validation/get_commit_dates.py
#         python3 code/validate_truth.py
    - name: Commit files
      env:
        AUTH: ${{ secrets.GITHUBTOKEN }}
      run: |
        git config user.email "action@github.com"
        git config user.name "GitHub Action - Vis/Val/Eval Update"
        git add --all
        git diff-index --quiet HEAD || git commit -m "Daily Vis/Val/Eval update"
        git push
        echo "pushed to github"
